### Lost And Found
GET https://cms.yukayamamoto.me/api/lost-and-founds

###
GET https://cms.yukayamamoto.me/api/lost-and-founds/1

###
POST https://cms.yukayamamoto.me/api/lost-and-founds
Content-Type: application/json

{
  "data":{
    "Title":"New Test task from API test",
    "Location":"test location",
    "LostOrFound": "Lost",
    "Email": "test@email.com",
    "Phonenumber": "000-000-000",
    "Description": "Something",
    "Image":"https://images.unsplash.com/photo-1521369909029-2afed882baee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
    "Date_found":"2022-01-07",
    "Claim_name": "Test Name"
  }
}

###
PUT https://cms.yukayamamoto.me/api/lost-and-founds/3
Content-Type:  application/json

{
  "data":{
    "Title":"New Test task from API test",
    "Location":"test location",
    "Claim": false,
    "Found": false,
    "LostOrFound": "Lost",
    "Email": "test@email.com",
    "Phonenumber": "000-000-000",
    "Description": "Something",
    "Image":"https://images.unsplash.com/photo-1521369909029-2afed882baee?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1740&q=80",
    "Date_found":"2022-06-07",
    "Claim_name": "Test Name"
  }
}


###
POST https://cms.yukayamamoto.me/api/leads
Content-Type: application/json

{
   "data":{
    "Name":"Test",
    "Email":"test@tes.com",
    "Message":"Some test message from local"
   }
}


### Portfolio
GET https://cms.yukayamamoto.me/api/skills?populate=*

###
GET https://cms.yukayamamoto.me/api/projects-portfolios?populate=deep

###
GET http://localhost:1337/api/projects-portfolios?populate=*

###
GET https://cms.yukayamamoto.me/api/projects-portfolios/1?populate=deep

###
POST http://localhost:1337/api/contact-portfolios
Content-Type: application/json

{
   "data":{
    "ClientName":"Test",
    "ClientEmail":"test@tes.com",
    "Message":"Some test message from local"
   }
}

###
POST https://cms.yukayamamoto.me/api/contact-portfolios
Content-Type: application/json

{
   "data":{
    "ClientName":"Test",
    "ClientEmail":"test@tes.com",
    "Message":"Some test message from local"
   }
}

###
GET https://cms.yukayamamoto.me/api/front-end-skills?populate=deep


###
POST https://cms.yukayamamoto.me/api/auth/local
Content-Type: application/json

{
  "identifier": "bill@bill.com",
  "password": "123456"
}






### Authroization
### Register (Also, you can create a new default user by usign Strapi admin screen)
POST http://localhost:1337/api/auth/local/register
Content-Type: application/json

{
    "username":"New",
    "email": "new@new.com",
    "password":"123456"
}

### Authenticate an user (You can authenticate a user by sending a POST request)
POST http://localhost:1337/api/auth/local
Content-Type: application/json

{
  "identifier": "yamamoto_yuka@hotmail.com",
  "password": "123456"
}


### Authenticate an user (You can authenticate a user by sending a POST request)
POST https://cms.yukayamamoto.me/api/auth/local
Content-Type: application/json

{
  "identifier": "yamamoto_yuka@hotmail.com",
  "password": "123456"
}


### Update user info
PUT http://localhost:1337/api/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU5NDg5MDc3LCJleHAiOjE2NjIwODEwNzd9.QSB6dUu7u7UejEKZ6NIzGbvTH0B-RxbxTRgbaspwWs4
{
  "username": "mary",
  "email": "mary@mary.com"
}


### forgotPassword
POST http://localhost:1337/api/auth/forgot-password
Content-Type: application/json

{
  "email": "yamamoto_yuka@hotmail.com",
  "url": "http://localhost:4200/trunkrecords/account/password"
}

###
POST  https://cms.yukayamamoto.me/api/auth/forgot-password
Content-Type: application/json

{
  "email": "yamamoto_yuka@hotmail.com",
  "url": "http://localhost:4200/trunkrecords/account/password"
}



###
POST http://localhost:1337/api/auth/reset-password
Content-Type: application/json

{
    "code": "privateCode",
    "password": "myNewPassword",
    "passwordConfirmation": "myNewPassword"
}


### Accessed your generated JWT token
GET http://localhost:1337/api/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjU4ODU1NzQxLCJleHAiOjE2NjE0NDc3NDF9.BGyj5wHGqeMty9DWHZE_RXeo2ozOQW4n2InhTfZ6pe0

### Password change






###  
PUT  https://cms.yukayamamoto.me/api/users/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjU5NDg5MjQ4LCJleHAiOjE2NjIwODEyNDh9.kV2dBZaWFK4vKxUCLarH-aNpGto0bFRMvAbFzkTLIbE

{
  "username": "updated",
  "email": "test@test.com"
}

### 
GET https://cms.yukayamamoto.me/api/apparelpages?populate=*


###
GET https://cms.yukayamamoto.me/api/home-page


###
GET https://cms.yukayamamoto.me/api/about-portfolio?populate=*

###
GET http://localhost:1337/api/apparelpages?pagination[page]=1

